export const SAMPLE_DETAILS_REQUEST = 'SAMPLE_DETAILS_REQUEST';
export const SAMPLE_DETAILS_SUCCESS = 'SAMPLE_DETAILS_SUCCESS';
export const SAMPLE_DETAILS_FAIL = 'SAMPLE_DETAILS_FAIL';

export const SAMPLE_LIST_REQUEST = 'SAMPLE_LIST_REQUEST';
export const SAMPLE_LIST_SUCCESS = 'SAMPLE_LIST_SUCCESS';
export const SAMPLE_LIST_FAIL = 'SAMPLE_LIST_FAIL';
